### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by fisx** [louispan/glazier-react#6]
Hi, I'm using (and [maintaining](https://github.com/liqula/react-hs)) John Lenz's react-flux binding.  After browsing glazier-react for 20 seconds I think I like it a lot.  I am opening this issue to let you know we exist.

What are your plans with this?  Are you using the code in production?  Should we talk about joining efforts and merging the two bindings?  (This would be a mid-term plan, we won't have much time to spend on this in the next two months.)

Can I add a mention of react-hs to the README?

Thanks!

**Comment by louispan** [comment]
Hi fisx,

Thanks for your interest!

At the moment glazier-react is just a personal hobby project, and no one used it in production, but on the upside it means I can keep experimenting with new ideas.

My current goals are:

- add ExceptT to the transformer stack underneath GadgetT for the Alternative instance allows composing duplicated parts of gadgets.
 - create an [Elm-like debugger](http://debug.elm-lang.org/edit/Mario.elm) to demonstrate state serialization and deserialzation

Regarding joining the two bindings, I'm open to collaboration, but ultimately I don't think it will be possible to combine the two bindings.

react-flux is based on the Flux design, whereas I'm using GadgetT from my [glazier](https://github.com/louispan/glazier) library for the update and state logic.

The way glazier-react binds to react is also very different - every widget uses the same [shim component](https://github.com/louispan/glazier-react#simple-and-efficient-reactcomponent-integration) and the only methods are required are setState, render and componentDidUpdate. This is because GadgetT takes a lot of the responsibility and burden of state update logic from React.

react-flux is a great library, without which I wouldn't have been able to get very far with glazier-react. Among the ideas I've used are:

- efficient and safe lazy parsing of event fields of react SyntheticEvent by using `seq`
- Use of blaze/lucid inspired writer monad for composing html
- Use of C #ifdef to allow compiling in both GHC and GHCJS.

However, you may be able to reuse some of the code I have written into a separate libraries.

- I have expanded #ifdef idea into [ghcjs-base-stub](https://github.com/louispan/ghcjs-base-stub), which allows any ghcjs project to compile under ghc - this allows for using IDE tools like intero for ghcjs projects!
- [javascript-extras](https://github.com/louispan/javascript-extras) contains IMHO safer conversion functions from JSVal than the ones provided in ghcjs-base. You may find that also useful.
- [disposables](https://github.com/louispan/disposable) is another library I wrote to help manage the cleanup of GHCJS callbacks.

Since react-hs is different from glazier-react, I don't think I'll mention it in the README at this stage. Maybe later when I expand the README, I'll acknowledge all other react-binding libraries to help users discover them.

**Comment by louispan** [comment]
It's a good thing we didn't merge bindings. I ended up using a completely different way of modelling widgets.

A gadget is now `ReaderT entity (ContT (State [cmds])) events`, and window is a `RWST (Scene s) () [ReactMarkup] ()`. A widget is a `ExceptT window Gadget`

I don't have any documentation on this method - it was the result of my continued experimentation of trying to write composable widgets. I'll focus on adding documentation https://github.com/louispan/glazier-react/issues/8.
